### ISSUE TITLE
Compiling and generating new ISO

### ISSUE THREAD

**Issue by calderonth** [GDSSecurity/EvilAbigail#1]
Hey, I'm trying to compile and run your tool and I am having issues to get a bootable ISO file.

Your instructions lack how to inject the dependencies in the TinyCore bit, but I think I've worked my way around this.
However, the ISO that is being generated is not bootable.
I always end up with a kernel panic at boot time, so I'm guessing the instructions on how to unpack everything in `core.d` and `Core-current` might be misleading.

Can you hep out?

**Comment by psychomario** [comment]
If you follow the instructions [here: remastering](http://wiki.tinycorelinux.net/wiki:remastering) you should be able to unpack the ISO to `Core-current`. With this directory in place, you can use the `Makefile` to build the `core.d` target which unpacks the `core.gz` filesystem.

To add the packages just use `unsquashfs` to extract the appropriate `tcz` files into `core.d`

**Comment by calderonth** [comment]
Thanks @psychomario managed to get it working.

Cheers!

**Comment by remi-cc** [comment]
Well, i missed something to generate a functionnal iso...

**What i have done:**
- unpack "core-current.iso" (v9 - x86 from http://distro.ibiblio.org/tinycorelinux/9.x/x86/release/Core-current.iso) into "core-current" directory
- "make core.d" to unpack core.gz into "core.d" directory
- download all prerequisites tcz files (v9 - x86 from http://distro.ibiblio.org/tinycorelinux/9.x/x86/tcz/)  listed in readme.me file : bzip2-lib.tcz, filesystems-4.14.10-tinycore.tcz, gdbm.tcz, libffi.tcz, mtd-4.14.10-tinycore.tcz, ncurses.tcz, openssl.tcz, python.tcz, readline.tcz, sqlite3.tcz
- "unsquashfs -f -d core.d/ python.tcz" (and all others tcz files downloaded at the previous step)
- verify that uncompressed files are in core.d directory (like "core.d/usr/local/tce.installed/python")
- "LHOST=192.168.1.50 make iso rev.so" to generate iso with my specified listening server IP @ (well, i changed depreciated "mkisofs" by "genisoimage" command in Makefile
**=> no errors, EvilAbigail.iso is build** (size of appro. 36Mb)
- i made a bootable usb key with this iso file, then i rebooted my FDE laptop (ubuntu 17.10) on this USB device
=> Core asks me to press "enter" to begin (or F2, F3, F4 to enter boot option). When i press "enter" to boot, core kernel is loading then shows me a shell "tc@box:~$" but nothing happens...
The /evilmaid.py script is present, like /hda1 file. /usr/local/tce.installed/python is present too for example, meaning that tcz unsquashed previously have been integrated in the iso file.
=> when i manualy execute command : "sudo /usr/local/tce.installed/python /evilmaid.py", nothing happens too.

Any ideas please?

Regards,

Rémi

**Comment by psychomario** [comment]
When you manually execute `python /evilmaid.py`, what do you mean by 'nothing happens'? No output at all or is there an error?

**Comment by remi-cc** [comment]
No output, no error, just a newline in the shell "tc@box:~$" like if a pressed "enter".
And i execute absolute path for python command  "sudo /usr/local/tce.installed/python" because this folder isn't in the PATH environment.

**Comment by remi-cc** [comment]
Well, i keep forward.
In fact, "/usr/local/tce.installed/python" is a shell script which extracts a tar.gz file.
This script should execute "tar xzf /usr/local/share/python/files/files.tar.gz -C /"
=> **but the script failed (without errors in stderr) because of denied access**
When i launch this command manualy with sudo ("sudo tar xzf /usr/local/share/python/files/files.tar.gz -C /"), it extracts a lot of python files like "/usr/local/bin/python 2.7"
Ok, then when i launch "sudo python /evilmaid.py", import curses is a problem...
=> It seems that all my prerequisites tcz files (python, ncurses and so on) hasn't been properly imported in the kernel
Did i miss to execute a command after all my "unsquashfs", in order to update the kernel with these new extracted tcz modules?

Thanks!

**Comment by psychomario** [comment]
The instructions for properly inserting tcz files is linked in [comment 2](https://github.com/GDSSecurity/EvilAbigail/issues/1#issuecomment-282043018). Please follow those and see if they resolve your issue.
